name: CI
on:
  push:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-arch:
    name: Build

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            name: amd
          - os: ubuntu-24.04-arm
            name: arm

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        id: attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Generate artifacts
        shell: bash
        env:
          attestation_url: ${{ steps.attestation.outputs.attestation-url }}
          image_id: ${{ steps.push.outputs.imageid }}
          digest: ${{ steps.push.outputs.digest }}
        run: |
          (
            echo "image_id: $image_id"
            echo "attestation_url: $attestation_url"
            echo "digest: $digest"
            echo "pull_url: $REGISTRY/$IMAGE_NAME:$digest"
          ) > outputs.yml

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: outputs-${{ matrix.name }}
          path: outputs.yml

  combine-images:
    name: Combine images
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    needs:
      - build-arch

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: false
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Collect
        id: collect
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
          q: '"'
          # run_id: 13704510562
        run: |
          gh run download \
            -R "$GITHUB_REPOSITORY" \
            ${run_id:-$GITHUB_RUN_ID} \
            -p 'outputs-*'
          get_field() {
            field="$1" perl -ne 'next unless s/$ENV{field}: //;print' "$output"
          }
          for output in outputs-*/outputs.yml; do
            arch=$(echo "$output" |perl -pe 's,/.*,,;s/outputs-//')
            digest=$(get_field digest)
            pull_url=$(get_field pull_url)
            attestation_url=$(get_field attestation_url)

            sha=$(curl -q -s -L "$attestation_url/download"| jq -r .dsseEnvelope.payload|base64 -d|jq -r '.subject[].digest.sha256')

            (
              echo '```json'
              echo '{'
              echo "  ${q}arch${q}: ${q}$arch${q},"
              echo "  ${q}sha${q}: ${q}$sha${q},"
              echo "  ${q}attestation_url${q}: ${q}$attestation_url${q}",
              echo "  ${q}pull_url${q}: ${q}$pull_url${q}"
              echo '}'
              echo '```'
              echo
            ) >> "$GITHUB_STEP_SUMMARY"
            echo "$REGISTRY/$IMAGE_NAME@$digest" >> sources
          done
          echo "sources=$(cat sources|perl -pe 's/^/"/;s/$/"/'|jq -c -s '.')" >> $GITHUB_OUTPUT

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - uses: int128/docker-manifest-create-action@v2
        id: build
        with:
          index-annotations: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          sources: ${{ fromJson(steps.collect.outputs.sources) }}

      - name: Generate artifact attestation
        id: attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true
